### ISSUE TITLE
configured to use notarytool but still uses altool

### ISSUE THREAD

**Issue by getneil** [electron/notarize#148] opened 2023-07-19 01:09 UTC
Hi thank you for building this tool,

Just needed help for this log not sure if it might just be a logging issue.
<img width="1003" alt="Screenshot 2023-07-19 at 9 05 57 AM" src="https://github.com/electron/notarize/assets/7913978/6d3796c6-9e5e-4549-be92-85e3908f0088">

The run is here: https://github.com/teaxyz/gui/actions/runs/5593877701/jobs/10228077743

the notarization code is in the electron-builder config:
```
      await notarize({
        tool: "notarytool",
        appBundleId,
        appPath,
        appleId: process.env.APPLE_ID,
        appleIdPassword: process.env.APPLE_APP_SPECIFIC_PASSWORD,
        teamId: process.env.APPLE_TEAM_ID
      });
```

**Comment by sprout2000** [comment] 2023-07-22 00:08
Hello.
I think if you give up the multi-architecture build in your "electron-builder.config.cjs" the notarytool mode will be correctly applied.

```diff
  mac: {
    icon: "./electron/icon.icns",
    target: {
      target: process.env.MAC_BUILD_TARGET || "default",
-     arch: ["x64", "arm64"]
+     arch: ["arm64"]
    },
    minimumSystemVersion: "11"
  },
```

See [https://github.com/electron/notarize/issues/150](https://github.com/electron/notarize/issues/150) for more details.

**Comment by MarshallOfSound** [comment] 2023-07-22 05:20
Closing as duplicate of #150, seems like a bug in builder

**Closed by MarshallOfSound** 2023-07-22 05:20 UTC
